#:include '../src/common.fypp'
#:set PROGRAM_NAME = 'check_nan'
program ${PROGRAM_NAME}$

#:for REAL_KIND in REAL_KINDS
    use, intrinsic :: iso_fortran_env, only: ${REAL_KIND}$
#:endfor

    use, intrinsic :: ieee_arithmetic, only: ieee_is_nan

    use, non_intrinsic :: arithmetic_geometric_mean_fortran

    use, non_intrinsic :: ieee_class_fortran



    implicit none



#:for REAL_KIND in REAL_KINDS
    call test_${REAL_KIND}$
#:endfor



    contains
#:for REAL_KIND in REAL_KINDS



    #:set SUBROUTINE_NAME = 'test_kernel_' + REAL_KIND
    subroutine ${SUBROUTINE_NAME}$(x, nan)

        real(${REAL_KIND}$), intent(in) :: x, nan



        real(${REAL_KIND}$) :: agm

        type(arithmetic_geometric_mean_${REAL_KIND}$_type) :: list



        agm = arithmetic_geometric_mean(x, nan)

        if ( .not. ieee_is_nan(agm) ) error stop

        agm = arithmetic_geometric_mean(nan, x)

        if ( .not. ieee_is_nan(agm) ) error stop



        call list%compute(x, nan)

        if ( .not. ieee_is_nan( max(list) ) ) error stop

        call list%compute(nan, x)

        if ( .not. ieee_is_nan( max(list) ) ) error stop

    end subroutine ${SUBROUTINE_NAME}$
    #:del SUBROUTINE_NAME



    #:set SUBROUTINE_NAME = 'test_' + REAL_KIND
    subroutine ${SUBROUTINE_NAME}$

        real(${REAL_KIND}$) :: agm, x, y

        type(arithmetic_geometric_mean_${REAL_KIND}$_type) :: list



        call set_ieee_quiet_nan(y)



        call test_kernel_${REAL_KIND}$( x = -1.0_${REAL_KIND}$, nan = y )
        call test_kernel_${REAL_KIND}$( x =  0.0_${REAL_KIND}$, nan = y )
        call test_kernel_${REAL_KIND}$( x =  1.0_${REAL_KIND}$, nan = y )



        call set_ieee_quiet_nan(x)



        agm = arithmetic_geometric_mean(x, y)

        if ( .not. ieee_is_nan(agm) ) error stop

        call list%compute(x, y)

        if ( .not. ieee_is_nan( max(list) ) ) error stop

    end subroutine ${SUBROUTINE_NAME}$
    #:del SUBROUTINE_NAME
#:endfor

end program ${PROGRAM_NAME}$
