#:include '../src/common.fypp'
#:set PROGRAM_NAME = 'check_nominal'
program ${PROGRAM_NAME}$

#:for REAL_KIND in REAL_KINDS
    use, intrinsic :: iso_fortran_env, only: ${REAL_KIND}$
#:endfor

    use, intrinsic :: ieee_arithmetic, only: ieee_is_normal
    use, intrinsic :: ieee_arithmetic, only: ieee_next_after
    use, intrinsic :: ieee_arithmetic, only: ieee_value

    use, non_intrinsic :: arithmetic_geometric_mean_fortran



    implicit none



#:for REAL_KIND in REAL_KINDS
    call test_${REAL_KIND}$
#:endfor



    contains
#:for REAL_KIND in REAL_KINDS



    #:set SUBROUTINE_NAME = 'test_' + REAL_KIND
    subroutine ${SUBROUTINE_NAME}$

        real(${REAL_KIND}$) :: agm, x, y

        type(arithmetic_geometric_mean_${REAL_KIND}$_type) :: list



        x = 1.0_${REAL_KIND}$



        y = tiny(y)

        agm = arithmetic_geometric_mean(x, y)

        if ( .not. ieee_is_normal(agm) ) error stop

        call list%compute(x, y)

        if ( .not. ieee_is_normal( max(list) ) ) error stop

        agm = arithmetic_geometric_mean(y, x)

        if ( .not. ieee_is_normal(agm) ) error stop

        call list%compute(y, x)

        if ( .not. ieee_is_normal( max(list) ) ) error stop



        y = epsilon(y)

        agm = arithmetic_geometric_mean(x, y)

        if ( .not. ieee_is_normal(agm) ) error stop

        call list%compute(x, y)

        if ( .not. ieee_is_normal( max(list) ) ) error stop

        agm = arithmetic_geometric_mean(y, x)

        if ( .not. ieee_is_normal(agm) ) error stop

        call list%compute(y, x)

        if ( .not. ieee_is_normal( max(list) ) ) error stop



        x   = sqrt( huge(x) )
        y   = ieee_next_after(x, 0.0_${REAL_KIND}$)

        agm = arithmetic_geometric_mean(x, y)

        if ( .not. ieee_is_normal(agm) ) error stop

        call list%compute(x, y)

        if ( .not. ieee_is_normal( max(list) ) ) error stop

        agm = arithmetic_geometric_mean(y, x)

        if ( .not. ieee_is_normal(agm) ) error stop

        call list%compute(y, x)

        if ( .not. ieee_is_normal( max(list) ) ) error stop

    end subroutine ${SUBROUTINE_NAME}$
    #:del SUBROUTINE_NAME
#:endfor

end program ${PROGRAM_NAME}$
