#:include '../src/common.fypp'
#:set PROGRAM_NAME = 'check_zero'
program ${PROGRAM_NAME}$

#:for REAL_KIND in REAL_KINDS
    use, intrinsic :: iso_fortran_env, only: ${REAL_KIND}$
#:endfor

    use, non_intrinsic :: arithmetic_geometric_mean_fortran

    use, non_intrinsic :: ieee_class_fortran



    implicit none



#:for REAL_KIND in REAL_KINDS
    call test_${REAL_KIND}$
#:endfor



    contains
#:for REAL_KIND in REAL_KINDS



    #:set SUBROUTINE_NAME = 'test_kernel_' + REAL_KIND
    subroutine ${SUBROUTINE_NAME}$(x, zero)

        real(${REAL_KIND}$), intent(in) :: x, zero



        real(${REAL_KIND}$) :: agm



        agm = arithmetic_geometric_mean(x, zero)

        if ( .not. is_ieee_positive_zero(agm) ) error stop

        agm = arithmetic_geometric_mean(zero, x)

        if ( .not. is_ieee_positive_zero(agm) ) error stop

    end subroutine ${SUBROUTINE_NAME}$
    #:del SUBROUTINE_NAME



    #:set SUBROUTINE_NAME = 'test_' + REAL_KIND
    subroutine ${SUBROUTINE_NAME}$

        real(${REAL_KIND}$) :: agm, x, y



        call set_ieee_positive_zero(y)



        call test_kernel_${REAL_KIND}$( x = 1.0_${REAL_KIND}$, zero = y )

        call test_kernel_${REAL_KIND}$( x = huge(x), zero = y )



        call set_ieee_positive_zero(x)



        agm = arithmetic_geometric_mean(x, y)

        if ( .not. is_ieee_positive_zero(agm) ) error stop

        agm = arithmetic_geometric_mean(y, x)

        if ( .not. is_ieee_positive_zero(agm) ) error stop

    end subroutine ${SUBROUTINE_NAME}$
    #:del SUBROUTINE_NAME
#:endfor

end program ${PROGRAM_NAME}$
