#:include '../src/common.fypp'
#:set PROGRAM_NAME = 'check_one'
program ${PROGRAM_NAME}$

#:for REAL_KIND in REAL_KINDS
    use, intrinsic :: iso_fortran_env, only: ${REAL_KIND}$
#:endfor

    use, non_intrinsic :: arithmetic_geometric_mean_fortran

    use, non_intrinsic :: ieee_class_fortran



    implicit none



#:for REAL_KIND in REAL_KINDS
    call test_${REAL_KIND}$
#:endfor



    contains
#:for REAL_KIND in REAL_KINDS



    #:set SUBROUTINE_NAME = 'test_' + REAL_KIND
    subroutine ${SUBROUTINE_NAME}$

        real(${REAL_KIND}$), parameter :: one = 1.0_${REAL_KIND}$

        real(${REAL_KIND}$) :: agm

        type(arithmetic_geometric_mean_${REAL_KIND}$_type) :: list



        agm = arithmetic_geometric_mean(one, one)

        if ( .not. is_ieee_positive_zero(agm - one) ) error stop



        call list%compute(one, one)

    #:for MAX_OR_MIN in MAX_AND_MIN
        if ( .not. is_ieee_positive_zero( ${MAX_OR_MIN}$(list) - one ) ) error stop
    #:endfor
    #:del MAX_OR_MIN
        if ( .not. is_ieee_positive_zero( gap(list)       ) ) error stop

        if ( ${N_ITER}$(list) .ne. 1 ) error stop

    end subroutine ${SUBROUTINE_NAME}$
    #:del SUBROUTINE_NAME
#:endfor

end program ${PROGRAM_NAME}$
