        !! Compute arithmetic–geometric mean using the given arithmetic mean `a` and geometric mean `g`.
        !!
        !! @warning
        !! - This function/interface assumes both inputs are positive.
        !! - No validation is performed on inputs.
        !! @endwarning
        !!
        !! @note
        !! **Convergence criterion**  
        !! See [[is_not_converged]]
        !! @endnote

